# Errors

- [Errors](#errors)
  - [basic](#basic)

## basic

simple usage of `errors.New()` or `fmt.Errorf()`

```go
package main

import (
	"fmt"
)

func f1(arg int) (int, error) {
	if arg == 42 {
		// return -1, errors.New("can't work with 42")
		return -1, fmt.Errorf("can't work with %d", arg)
	}
	return arg + 3, nil
}

func main() {
	for _, i := range []int{7, 42} {
		if r, e := f1(i); e != nil {
			fmt.Println("f1 failed:", e)
		} else {
			fmt.Println("f1 worked:", r)
		}
	}
}
```

custom errors

```go
package main

import (
	"fmt"
)

type argError struct {
	arg  int
	prob string
}

func (e *argError) Error() string {
	return fmt.Sprintf("%d - %s", e.arg, e.prob)
}

func f2(arg int) (int, error) {
	if arg == 42 {
		// because func (e *argError) Error(), we should use &argError{}
		return -1, &argError{arg, "can't work with it"}
	}
	return arg + 3, nil
}

func main() {
	for _, i := range []int{7, 42} {
		if r, e := f2(i); e != nil {
			fmt.Println("f1 failed:", e)
		} else {
			fmt.Println("f1 worked:", r)
		}
	}
}
```

recommened custom errors

```go
package main

import (
	"fmt"
)

type argError struct {
	arg  int
	prob string
}

func (e argError) Error() string {
	return fmt.Sprintf("%d - %s", e.arg, e.prob)
}

func f2(arg int) (int, error) {
	if arg == 42 {
		return -1, argError{arg, "can't work with it"}
	}
	return arg + 3, nil
}

func main() {
	for _, i := range []int{7, 42} {
		if r, e := f2(i); e != nil {
			fmt.Println("f1 failed:", e)
		} else {
			fmt.Println("f1 worked:", r)
		}
	}
}
```

return custom errors of `nil`

```go
package main

import (
	"fmt"
)

type Status int

const (
	InvalidLogin Status = iota + 1
	NotFound
)

type StatusErr struct {
	Status  Status
	Message string
}

func (se StatusErr) Error() string {
	return se.Message
}

func GenerateError1(flag bool) error {
	var genErr error
	if flag {
		genErr = StatusErr{
			Status: NotFound,
		}
	}
	return genErr
}

func GenerateError2(flag bool) error {
	if flag {
		return StatusErr{
			Status: NotFound,
		}
	}
	return nil
}

// terrible
func GenerateError3(flag bool) error {
	var genErr StatusErr // shouldn't be StatusErr, should be error
	if flag {
		genErr = StatusErr{
			Status: NotFound,
		}
	}
	return genErr
}

func main() {
	{
		err := GenerateError1(true)
		fmt.Println(err != nil) // true
		err = GenerateError1(false)
		fmt.Println(err != nil) // false
	}
	{
		err := GenerateError2(true)
		fmt.Println(err != nil) // true
		err = GenerateError2(false)
		fmt.Println(err != nil) // false
	}
	{
		err := GenerateError3(true)
		fmt.Println(err != nil) // true
		err = GenerateError3(false)
		fmt.Println(err != nil) // true
	}
}
```