# Errors

- [Errors](#errors)
  - [basic](#basic)
  - [`errors.As()`, `errors.Is()`](#errorsas-errorsis)
  - [`errors.Unwrap()`](#errorsunwrap)

## basic

simple usage of `errors.New()` or `fmt.Errorf()`

```go
package main

import (
	"fmt"
)

func f1(arg int) (int, error) {
	if arg == 42 {
		// return -1, errors.New("can't work with 42")
		return -1, fmt.Errorf("can't work with %d", arg)
	}
	return arg + 3, nil
}

func main() {
	for _, i := range []int{7, 42} {
		if r, e := f1(i); e != nil {
			fmt.Println("f1 failed:", e)
		} else {
			fmt.Println("f1 worked:", r)
		}
	}
}
```

custom errors by implementing `Error()`

```go
package main

import (
	"fmt"
)

type argError struct {
	arg  int
	prob string
}

func (e *argError) Error() string {
	return fmt.Sprintf("%d - %s", e.arg, e.prob)
}

func f2(arg int) (int, error) {
	if arg == 42 {
		// because func (e *argError) Error(), we should use &argError{}
		return -1, &argError{arg, "can't work with it"}
	}
	return arg + 3, nil
}

func main() {
	for _, i := range []int{7, 42} {
		if r, e := f2(i); e != nil {
			fmt.Println("f1 failed:", e)
		} else {
			fmt.Println("f1 worked:", r)
		}
	}
}
```

recommened custom errors with *value receiver*

```go
package main

import (
	"fmt"
)

type argError struct {
	arg  int
	prob string
}

func (e argError) Error() string {
	return fmt.Sprintf("%d - %s", e.arg, e.prob)
}

func f2(arg int) (int, error) {
	if arg == 42 {
		return -1, argError{arg, "can't work with it"}
	}
	return arg + 3, nil
}

func main() {
	for _, i := range []int{7, 42} {
		if r, e := f2(i); e != nil {
			fmt.Println("f1 failed:", e)
		} else {
			fmt.Println("f1 worked:", r)
		}
	}
}
```

return custom errors of `nil`

```go
package main

import (
	"fmt"
)

type Status int

const (
	InvalidLogin Status = iota + 1
	NotFound
)

type StatusErr struct {
	Status  Status
	Message string
}

func (se StatusErr) Error() string {
	return se.Message
}

func GenerateError1(flag bool) error {
	var genErr error
	if flag {
		genErr = StatusErr{
			Status: NotFound,
		}
	}
	return genErr
}

func GenerateError2(flag bool) error {
	if flag {
		return StatusErr{
			Status: NotFound,
		}
	}
	return nil
}

// terrible
func GenerateError3(flag bool) error {
	var genErr StatusErr // shouldn't be StatusErr, should be error
	if flag {
		genErr = StatusErr{
			Status: NotFound,
		}
	}
	return genErr
}

func main() {
	{
		err := GenerateError1(true)
		fmt.Println(err != nil) // true
		err = GenerateError1(false)
		fmt.Println(err != nil) // false
	}
	{
		err := GenerateError2(true)
		fmt.Println(err != nil) // true
		err = GenerateError2(false)
		fmt.Println(err != nil) // false
	}
	{
		err := GenerateError3(true)
		fmt.Println(err != nil) // true
		err = GenerateError3(false)
		fmt.Println(err != nil) // true
	}
}
```

## `errors.As()`, `errors.Is()`

`errors.As()` and `errors.Is()` are used to check if an error is of a specific type

```go
package main

import (
	"errors"
	"fmt"
)

type argError struct {
	arg  int
	prob string
}

func (e argError) Error() string {
	return fmt.Sprintf("%d - %s", e.arg, e.prob)
}

func f2(arg int) (int, error) {
	if arg == 42 {
		return -1, argError{arg, "can't work with it"}
	}
	return arg + 3, nil
}

func main() {
	_, e := f2(42)
	var myErr argError
	if errors.As(e, &myErr) {
		fmt.Println(myErr.arg, myErr.prob)
	}

	if errors.Is(e, myErr) {
		fmt.Println("there is some error") // invoked
	}
	if errors.Is(e, argError{42, "can't work with it"}) {
		fmt.Println("there is some error") // invoked
	}
}
```

```go
package main

import (
	"errors"
	"fmt"
)

type ResourceErr struct {
	Resource string
	Value    int
}

func (re ResourceErr) Error() string {
	return fmt.Sprintf("%s: %d", re.Resource, re.Value)
}

func (re ResourceErr) Code() int {
	return re.Value
}

func main() {
	err := ResourceErr{Value: 100}
	// declare an annoymous interface
	var coder interface{ Code() int }

	if errors.As(err, &coder) {
		fmt.Println(coder.Code()) // 100
	}
}
```

## `errors.Unwrap()`

`errors.Unwrap()` is a method that returns the underlying error of a wrapped error, used rarely

`fmt.Errorf("%w")` with `Unwrap()`
> if you don't want to the new error to be Unwrapable, use:  
> `return fmt.Errorf("in fileChecker: %v", err)`

```go
package main

import (
	"errors"
	"fmt"
	"os"
)

func fileChecker(name string) error {
	f, err := os.Open(name)
	if err != nil {
        // use %w to wrap previous error msg
		return fmt.Errorf("in fileChecker: %w", err)
	}
	f.Close()
	return nil
}

func main() {
	err := fileChecker("not_here.txt")
	if err != nil {
		fmt.Println(err)
		if wrappedErr := errors.Unwrap(err); wrappedErr != nil {
            // unwrap error msg of os.Open()
			fmt.Println(wrappedErr)
		}
	}
}
```

custom `Unwrap()`

```go
package main

import (
	"errors"
	"fmt"
	"os"
)

type Status int

const (
	InvalidLogin Status = iota + 1
	NotFound
)

type StatusErr struct {
	Status  Status
	Message string
	Err     error
}

func (se StatusErr) Error() string {
	return se.Message
}

func (se StatusErr) Unwrap() error {
	return se.Err
}

func fileChecker(name string) error {
	f, err := os.Open(name)
	if err != nil {
		return StatusErr{
			Status:  NotFound,
			Message: "File not found",
			Err:     err,
		}
	}
	f.Close()
	return nil
}

func main() {
	{
		err := fileChecker("hello.txt")
		if err != nil {
			fmt.Println(err) // File not found
			if wrappedErr := errors.Unwrap(err); wrappedErr != nil {
				fmt.Println(wrappedErr) // open hello.txt: The system cannot find the file specified.
			}
		}
	}
}
```

`errors.Is()` with `Unwrap()`

```go
package main

import (
	"errors"
	"fmt"
	"os"
)

func fileChecker(name string) error {
	f, err := os.Open(name)
	if err != nil {
		return fmt.Errorf("in fileChecker: %w", err)
	}
	f.Close()
	return nil
}
func main() {
	err := fileChecker("not_here.txt")
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			fmt.Println("That file doesn't exist")
		}
	}
}
```